/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million
 * find the sum of the even-valued terms.
 */

/**
 * Fn = (fi ** n - bi ** n)/sqrt(5)
 * bi = - 1/fi
 * Fn = (fi ** n - (-fi) ** (-n))/sqrt(5)
 */
int fib(int n) {
        double fi = (1 + sqrt(5))/2;
        double rs = (pow(fi, n) - pow(-fi, -n))/sqrt(5);
        return (int)rs;
}

int range = 4000000; //4 million

void solution1() {
        long counter = 0;
        int mask = 0x01;
        int i = 2, v = 0;
        while(v < range) {
                // if v is even
                if((mask & v) == 0) {
                        counter += v;
                        printf("%d\n", v);
                }
                v = fib(i++);
        }
        printf("sum:\t%ld\n",counter);
        return;
}

// fb: O O E O O E O O E...
// every third posisition is an even number
void solution2() {
        long counter = 0;
        int v = 0, i = 0;
        while(v < range) {
                v = fib(i);
                if(i % 3 == 0) {
                        counter += v;
                        printf("%d\n", v);
                }
                i++;
        }
        printf("sum:\t%ld\n",counter);
        return;
}

// get rid of th fib(n)
// just use iterative sum-up
void solution3() {
        long counter = 2;
        int i0 = 1, i1 = 1, i2 = 2;

        while(1) {
                i0 = i1 + i2;
                i1 = i2 + i0;
                i2 = i0 + i1;
                if(i0 >= range || i1 >= range || i2>=range) {
                        break;
                }
                counter += i2;
                printf("%d\n",i2);
        }
        printf("sum:\t%ld\n",counter);
        return;
}

int main() {
        solution2();
        return 0;
}

